[profile.default]
solc = "0.8.19"
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 5
optimizer = true
optimizer_runs = 20_000



# See more config options https://github.com/foundry-rs/foundry/tree/master/config